# Wildcard labels

brace_expansion: true

rules:
  - labels: [infrastructure]
    patterns: ['*|.github/**|!README.md']

  - labels: [source]
    patterns: ['label_bot/**']

  - labels: [docs]
    patterns: ['README.md']

  - labels: [wip-labels]
    patterns: ['label_bot/wip_labels.py']

  - labels: [triage-labels]
    patterns: ['label_bot/triage_labels.py']

  - labels: [review-labels]
    patterns: ['label_bot/review_labels.py']

  - labels: [wildcard-labels]
    patterns: ['label_bot/wildcard_labels.py']

  - labels: [sync-labels]
    patterns: ['label_bot/sync_labels.py']

  - labels: [lgtm-labels]
    patterns: ['label_bot/lgtm_labels.py']

  - labels: [add-remove-labels]
    patterns: ['label_bot/add_remove_labels.py']


labels:
- name: sync-labels
  color: subcategory
  description: Sync labels library.

- name: lgtm-labels
  color: subcategory
  description: LGTM labels library.

- name: add-remove-labels
  color: subcategory
  description: Add/remove labels library.

- name: wip-labels
  color: subcategory
  description: WIP labels library.

- name: triage-labels
  color: subcategory
  description: Triage label library.

- name: review-labels
  color: subcategory
  description: Review label library.

- name: wildcard-labels
  color: subcategory
  description: Wildcard labels library.
