# Wildcard labels

brace_expansion: true

rules:
  - labels: [infrastructure]
    patterns: ['*|.github/**|!README.md']

  - labels: [source]
    patterns: ['label_bot/**']

  - labels: [docs]
    patterns: ['README.md']

  - labels: [wip-labels]
    patterns: ['label_bot/wip_labels.py']

  - labels: [triage-labels]
    patterns: ['label_bot/triage_labels.py']

  - labels: [review-labels]
    patterns: ['label_bot/review_labels.py']

  - labels: [wildcard-labels]
    patterns: ['label_bot/wildcard_labels.py']

  - labels: [sync-labels]
    patterns: ['label_bot/sync_labels.py']

# WIP

wip:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected

# LGTM

lgtm_add:
  # Special entries for LGTM
  _pull_request: [approved]
  _issue: []

  # Normal entries
  docs: [docs]
  confirmed-bug: [bug, confirmed]
  enhancement: [enhancement]
  maintenance: [maintenance]
  feature: [feature]
  maybe: [maybe]

lgtm_remove:
  - triage
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected

# Label management

delete_labels: true

colors:
    bug: '#c45b46'
    feature: '#7b17d8'
    support: '#efbe62'
    maintenance: '#b2ffeb'
    category: '#709ad8'
    subcategory: '#bfd4f2'
    pending: '#f0f49a'
    rejected: '#f7c7be'
    approved: '#beed6d'
    low: '#dddddd'
    bot: '#000000'

labels:
- name: bug
  color: bug
  description: Bug report.

- name: feature
  color: feature
  description: Feature request.

- name: maintenance
  color: maintenance
  description: Maintenance chore.

- name: support
  color: support
  description: Support request.

- name: tests
  color: category
  description: Related to testing.

- name: infrastructure
  color: category
  description: Related to project infrastructure.

- name: source
  color: category
  description: Related to source code.

- name: docs
  color: category
  description: Related to documentation.

- name: sync-labels
  renamed: label-mgr
  color: subcategory
  description: Sync labels library.

- name: wip-labels
  color: subcategory
  description: WIP labels library.

- name: triage-labels
  color: subcategory
  description: Triage label library.

- name: review-labels
  color: subcategory
  description: Review label library.

- name: wildcard-labels
  color: subcategory
  description: Wildcard labels library.

- name: more-info-needed
  color: pending
  description: More information is required.

- name: needs-confirmation
  color: pending
  description: The alleged behavior needs to be confirmed.

- name: needs-decision
  color: pending
  description: A decision needs to be made regarding request.

- name: confirmed
  color: approved
  description: Confirmed bug report or approved feature request.

- name: maybe
  color: low
  description: Pending approval of low priority request.

- name: duplicate
  color: rejected
  description: The issue has been previously reported.

- name: wontfix
  color: rejected
  description: The issue will not be fixed for the stated reasons.

- name: invalid
  color: rejected
  description: Invalid report (user error, upstream issue, etc).

- name: triage
  color: pending
  description: Issue needs triage.

- name: work-in-progress
  color: pending
  description: A partial solution. More changes will be coming.

- name: needs-review
  color: pending
  description: Needs to be reviewed and/or approved.

- name: requires-changes
  color: pending
  description: Awaiting updates after a review.

- name: approved
  color: approved
  description: The pull request is ready to be merged.

- name: rejected
  color: rejected
  description: The pull request is rejected for the stated reasons.

- name: skip-triage
  color: bot
  description: Tells bot to not tag a new issue with 'triage'.

- name: skip-review
  color: bot
  description: Tells bot to not tag a reviews with 'needs-review'.
